version: 2.1

jobs:
  run_tests:
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command: |
            echo 'export PATH=~/.local/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV
            pip install --user -r requirments.txt
      - run:
          name: Run Unit Tests
          command: pytest --junitxml=test-reports/junit.xml --html=test-reports/pytest_report.html --self-contained-html
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports

workflows:
  build_test:
    jobs:
      - run_tests
